name: CI

on: [push]

jobs:
  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
      
    - name: Install .NET SDK 3.1
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y apt-transport-https git dotnet-sdk-3.1 dotnet-runtime-3.1
      
    - name: Pull source code
      run: |
        $BUILD_DIR = $HOME/build
        mkdir $BUILD_DIR && cd $BUILD_DIR
        git clone https://github.com/Bonifatius94/ChessAI.CS
        
    - name: Run build script
      run: chmod 777 build.sh && ./build.sh
    
    - name: Run test script
      run: chmod 777 test.sh && ./test.sh
      
    - name: Run package script
      run: chmod 777 package.sh && ./package.sh
